# .github/workflows/build-and-deploy.yml

name: Node.js CI

on:
  push:
    branches: [ nextjs ]

jobs:
  build:
		
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          # update the Node version to meet your needs
          node-version: 16
          cache: npm

      - name: Build
        run: |
          npm ci && cd about-me && npm i && cd ..
          # configure the build here

      - name: Deploy
        # configure an external GitHub Pages deploy workflow here
